spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_management?serverTimezone=UTC
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password:

api:
  list:
    host: localhost
    port: 8080
    path: /list
  detail:
    host: localhost
    port: 8080
    path: /detail
  timeout: 10000

product:
  categories:
    - car
    - motorcycle
    - bicycle

class:
  students:
    - student:
      name: Student A
      gender: male
    - student:
      name: Student B
      gender: male
    - student:
      name: Student C
      gender: female